version: "3.9"

x-enviroment: &environment
  ENV: 'main'

services:
  sd-service-server:
    build: .
    command: pipenv run uvicorn 'cmd.server:app' --app-dir src --workers 4 --host 0.0.0.0 --port 3000
#    command: pipenv run gunicorn 'app:app' --chdir src -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:3000
    environment: *environment
    volumes:
      - db-data:/data/
    ports:
      - "3000:3000"

  sd-service-scheduler:
    build: .
    command: pipenv run python src/cmd/scheduler.py
    environment: *environment
    volumes:
      - db-data:/data/

volumes:
  db-data:
