version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13.0-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
